In [9]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def tanh(x):
    return np.tanh(x)

# Sample sizes
input_size = 3
hidden_size = 4

# Sample input & previous states
x_t = np.random.randn(input_size, 1)
h_prev = np.zeros((hidden_size, 1))
c_prev = np.zeros((hidden_size, 1))

In [10]:
x_t

array([[-0.07923971],
       [-1.19530438],
       [-1.79888909]])

In [11]:
h_prev

array([[0.],
       [0.],
       [0.],
       [0.]])

In [12]:
c_prev

array([[0.],
       [0.],
       [0.],
       [0.]])

In [13]:
# Random weights & biases for gates
W_f = np.random.randn(hidden_size, hidden_size + input_size)  # Forget gate
b_f = np.random.randn(hidden_size, 1)

W_i = np.random.randn(hidden_size, hidden_size + input_size)  # Input gate
b_i = np.random.randn(hidden_size, 1)

W_c = np.random.randn(hidden_size, hidden_size + input_size)  # Candidate
b_c = np.random.randn(hidden_size, 1)

W_o = np.random.randn(hidden_size, hidden_size + input_size)  # Output gate
b_o = np.random.randn(hidden_size, 1)

In [17]:
W_f

array([[ 0.40781287, -1.66106141, -1.07706947,  0.71863997,  1.93791429,
        -2.03524573, -0.87395016],
       [ 0.05225409,  1.42411813,  0.23738836, -0.42652066,  1.16506385,
        -0.66698459, -0.502575  ],
       [ 0.67950041, -0.09260948,  1.03482443,  0.49144372,  1.28755562,
        -0.70997539,  2.16111943],
       [ 0.8942961 ,  0.56452645,  0.63415747,  2.2057057 ,  0.65750814,
         1.32760599, -0.35768907]])

In [5]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def tanh(x):
    return np.tanh(x)

# Sample sizes
input_size = 3
hidden_size = 4

# Sample input & previous states
x_t = np.random.randn(input_size, 1)
h_prev = np.zeros((hidden_size, 1))
c_prev = np.zeros((hidden_size, 1))

# Random weights & biases for gates
W_f = np.random.randn(hidden_size, hidden_size + input_size)  # Forget gate
b_f = np.random.randn(hidden_size, 1)

W_i = np.random.randn(hidden_size, hidden_size + input_size)  # Input gate
b_i = np.random.randn(hidden_size, 1)

W_c = np.random.randn(hidden_size, hidden_size + input_size)  # Candidate
b_c = np.random.randn(hidden_size, 1)

W_o = np.random.randn(hidden_size, hidden_size + input_size)  # Output gate
b_o = np.random.randn(hidden_size, 1)

# Concatenate input & previous hidden state
concat = np.vstack((h_prev, x_t))

# 1️⃣ Forget gate — what to remove
f_t = sigmoid(np.dot(W_f, concat) + b_f)

# 2️⃣ Input gate — what to write
i_t = sigmoid(np.dot(W_i, concat) + b_i)

# Candidate memory — possible new content
c_tilde = tanh(np.dot(W_c, concat) + b_c)

# 3️⃣ Update cell state
c_t = f_t * c_prev + i_t * c_tilde

# 4️⃣ Output gate — what to output
o_t = sigmoid(np.dot(W_o, concat) + b_o)

# Hidden state
h_t = o_t * tanh(c_t)

print("Forget gate f_t:\n", f_t)
print("Input gate i_t:\n", i_t)
print("Candidate memory c~:\n", c_tilde)
print("New cell state c_t:\n", c_t)
print("Output gate o_t:\n", o_t)
print("New hidden state h_t:\n", h_t)

Forget gate f_t:
 [[0.74156991]
 [0.54384824]
 [0.63753161]
 [0.54837901]]
Input gate i_t:
 [[0.87839026]
 [0.55294731]
 [0.3882278 ]
 [0.37801303]]
Candidate memory c~:
 [[-0.6010713 ]
 [ 0.27580447]
 [ 0.99186518]
 [-0.68085729]]
New cell state c_t:
 [[-0.52797517]
 [ 0.15250534]
 [ 0.38506963]
 [-0.25737293]]
Output gate o_t:
 [[0.2681797 ]
 [0.71980458]
 [0.294417  ]
 [0.28046168]]
New hidden state h_t:
 [[-0.12975386]
 [ 0.10893085]
 [ 0.10808108]
 [-0.07063055]]
